### PR TITLE
feat: add arm64 support

### PR DESCRIPTION
**Pull request by day01**
**CONTEXT**
BS from last version is not available on mac arm. 

**CHANGE SCOPE**
I added arm64 support in cpp file. 

**RESULT**
Tests pass correctly. Crate form dir is correctly works on mac. 

**ADDITIONAL**
I added gitignore because terget is in main dir generated in build process 🗑️

### CODE REVIEW

**Comment by hayden4r4** [comment]
Looks good, thanks for contributing!

**Comment by day01** [comment]
Do you need help with GitHub Actions to automate your deployments to crates.io?

**Comment by hayden4r4** [comment]
I was actually just looking at this the other day. I just set up build and test with github actions, are you familiar with getting cargo publish set up as well?  I'm not sure how the credentials work in that case.

**Comment by day01** [comment]
I am familiar with GHA, so it's not a problem to configure it. I am big enthusiasts of automation of packages :)

**Comment by day01** [comment]
So if you are interested in help in that area let me know. You can create issue and assign me. I am on vacation but in the next week I can help you with :)

**Comment by hayden4r4** [comment]
Great, I created an issue, I believe if you leave a comment on it I can assign you to it.

**Pull request merged**
